### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: library "libMNN.so" not found

### ISSUE THREAD

**Issue by SomeO** [yeyupiaoling/ClassificationForAndroid#1]
hi，I ran your code in Android Studio，do what you say in README，
I build mnn .so files, and put them in  src/main/jniLibs/,  total two folder *arm64-8v* and  *armeabi-v7a*. 
but I got this error ,
![image](https://user-images.githubusercontent.com/17061150/102467965-e6b22b00-408b-11eb-9014-8443aa571a07.png)

my compute's info:
  - windows 10
  - i5- 7300
 
![image](https://user-images.githubusercontent.com/17061150/102468194-30027a80-408c-11eb-97f9-19b67d55a6be.png)

I run code in an android Virtual Devices：
![image](https://user-images.githubusercontent.com/17061150/102468555-a0110080-408c-11eb-84b8-7c03062b1f1b.png)

I run a Virtual Device with CPU/ABI is arm64-8v or armeabi-v7a, it show 
```python
Error while waiting for device: The emulator process for AVD Pixel_4_API_30_arm64 was killed.
```

I try some other method to solve this, but failed, could you help me?

**Comment by yeyupiaoling** [comment]
我是用真机测试的。
