### ISSUE TITLE
使用YOLOv5训练的pt模型转tflite模型时出现了问题，麻烦帮我看一下

### ISSUE THREAD

**Issue by Jieams** [yeyupiaoling/ClassificationForAndroid#10]
![1698716282405](https://github.com/yeyupiaoling/ClassificationForAndroid/assets/31683898/be8119d2-2567-4d29-a235-21db8af9433f)
![1698716307130](https://github.com/yeyupiaoling/ClassificationForAndroid/assets/31683898/57d59730-804b-4b05-857b-be424e1e2653)
![1698716511332](https://github.com/yeyupiaoling/ClassificationForAndroid/assets/31683898/f0ad14dd-0232-4de0-ad54-70ecbd3a1511)

**Comment by yeyupiaoling** [comment]
Pytorch转换tflite？这个我没有试过。看着好像不是加载模型错误
