### ISSUE TITLE
大佬请教一下训练模型里面config的具体参数。我训练了很多模型，电脑端都能用，转到移动端就用不了。

### ISSUE THREAD

**Issue by MrWangChong** [yeyupiaoling/ClassificationForAndroid#11]
我用我的模型在你代码里面试了下报这个错。
java.lang.IllegalArgumentException: Input error: 'input_1' is not a valid name for any input. Names of inputs and their indexes are {serving_default_rescaling_input:0=0}

模型训练的IMG_SHAPE=(224, 224, 3) batch_size=16

**Comment by yeyupiaoling** [comment]
@MrWangChong 你这个是输入层名的问题，你的模型没有这个输入层名。要根据你模型的输入层修改输入名
