### ISSUE TITLE
TNN模块内存异常

### ISSUE THREAD

**Issue by XSeanLiu** [yeyupiaoling/ClassificationForAndroid#2]
TNN demo我们监控发现，内存会异常，物理内存使用率会越来越大，知道占满异常退出

**Comment by yeyupiaoling** [comment]
我当时测试并没有出现这个问题。你找下原因。如果是TNN内部的问题，去他们的github上提问。

**Comment by dlaoy** [comment]
TNN demo 实时预测确实有存在内存增大，最后导致应用闪退重启了。。。。
