### ISSUE TITLE
关于图像的均值和标准差

### ISSUE THREAD

**Issue by huangyuan2020** [yeyupiaoling/ClassificationForAndroid#3]
您好，非常感谢您提供的教程！
我看到关于设置图像均值和标准差的代码十分重要，我只接触过mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]这样的处理，这应该是适应imagenet预训练模型时大家通常采用的，看起来跟您的代码里的数字差别很大，请问您能告诉我您的代码里的图像均值和标准差是如何确定的吗？

**Comment by yeyupiaoling** [comment]
你这个实际上还有个除以255的操作的。具体是这样的
```python
img = (img/255.0 - [0.485, 0.456, 0.406]) / [0.229, 0.224, 0.225]
```
最终还是归一化都[-1, 1]

也有直接是
```python
img = (img - 127.5) / 127.5
```

其实也差不多的。使用那个都可以，

**Comment by huangyuan2020** [comment]
> 你这个实际上还有个除以255的操作的。具体是这样的
> 
> ```python
> img = (img/255.0 - [0.485, 0.456, 0.406]) / [0.229, 0.224, 0.225]
> ```
> 
> 最终还是归一化都[-1, 1]
> 
> 也有直接是
> 
> ```python
> img = (img - 127.5) / 127.5
> ```
> 
> 其实也差不多的。使用那个都可以，

我明白了，您的回复太及时了，非常感谢！

**Comment by yeyupiaoling** [comment]
没事我就关闭issue了
