### ISSUE TITLE
运行错误 java.lang.UnsatisfiedLinkError: dlopen failed: library "libomp.so" not found

### ISSUE THREAD

**Issue by Catheryan** [yeyupiaoling/ClassificationForAndroid#4]
![image](https://user-images.githubusercontent.com/14145561/129331040-dae7ce19-b7ae-45f2-b40c-2301b43758dc.png)
这个操作lib库是在哪里的呢？
System.loadLibrary("mnncore");

**Comment by yeyupiaoling** [comment]
MNN好像没有libomp.so这个的喔，你直接用Android studio打开就这样？
