### ISSUE TITLE
我用自己的模型进行推理

### ISSUE THREAD

**Issue by alanMachineLeraning** [yeyupiaoling/ClassificationForAndroid#8]
推理结果为空，请问是什么原因呢

**Comment by alanMachineLeraning** [comment]
我的是pytorch模型转成mnn的，我看您这边是tf模型转成mnn，这2种模型在使用nativeGetSessionOutput这个api获取推理结果的时候是不是有所不同？

**Comment by yeyupiaoling** [comment]
如果都是mnn模型，应该是一样的。注意看你的模型是怎样的，要对应的的输入输出。还有预处理。
