### ISSUE TITLE
想问下mnn版本是多少？

### ISSUE THREAD

**Issue by zhao028** [yeyupiaoling/ClassificationForAndroid#9]
我用一样的mobilenet模型按照命令转化后手机端跑不起来

**Comment by yeyupiaoling** [comment]
@zhao028 我也忘记了，如何你的是最新的，应该是支持的，你 看看有没有报什么错误，有没有转换成功

**Comment by zhao028** [comment]
> @zhao028 我也忘记了，如何你的是最新的，应该是支持的，你 看看有没有报什么错误，有没有转换成功

我重新编译了转化就成功了，谢谢！
